<a href="https://colab.research.google.com/github/Mo7amedAmin/IEEE_Tasks/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [84]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [85]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [86]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [87]:
# One-Dimensional array
import numpy as np
arr_1D = np.array([2000, 2002, 2007, 2015])
print(arr_1D.shape, arr_1D.dtype)






(4,) int64


In [88]:
# Two-Dimensional array
arr_2D = np.array([[12, 145, 26],
                   [37, 109, 88],
                   [210, 61, 98]])
print(arr_2D.shape, arr_2D.dtype)






(3, 3) int64


In [89]:
# Three-Dimensional array
arr_3D = np.array([[[True, False], [True, True]],
                   [[False, True], [True, False]],
                   [[False, False], [False, True]]])
print(arr_3D.shape, arr_3D.dtype)







(3, 2, 2) bool


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [90]:
# Method one

arr = np.array([[[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,10]]])

print(arr[:, ::-1, ::-1])






[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


In [91]:
# Method two
#>**hint**: use flipud function
arr = np.array([[[1,2,3,4],
                 [4,5,6,7],
                 [7,8,9,10]]])


np.flip(arr)






array([[[10,  9,  8,  7],
        [ 7,  6,  5,  4],
        [ 4,  3,  2,  1]]])

## 6-Make this array as an array one dimensional

In [92]:
arr.flatten()

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [93]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]], dtype=np.int16)
print(arr.shape)
print(arr.ndim)
print(arr.itemsize)

(3, 2)
2
2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

In [112]:
sampleArray = np.array([[3 ,6, 9, 12],
                        [15 ,18, 21, 24],
                        [27 ,30, 33, 36],
                        [39 ,42, 45, 48],
                        [51 ,54, 57, 60]])

sampleArray[0::2, 1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

## 9-How is np.mean() different from np.average() in NumPy?

In [95]:
arr = [1, 2, 3, 4, 5]
#np.mean() always computes the arithmetic mean
np.mean(arr)

3.0

In [96]:
#np.average() has an optional weights parameter used to compute a weighted average
np.average(arr)

3.0

In [97]:
np.average(arr, weights = [.1, .5, .3, .7, .4])

3.4

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [98]:
x = int(input())
arr = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
mask = arr==x
print(mask.sum())

1
2


## 11-Show how is arr[:,0] different from arr[:,[0]]

In [99]:
arr = np.array([[3, 6, 9, 12],
                        [15, 18, 21, 24],
                        [27, 30, 33, 36],
                        [39, 42, 45, 48],
                        [51, 54, 57, 60]])
arr[:,0] #return 1D_array of the first column


array([ 3, 15, 27, 39, 51])

In [100]:
arr[:,[0]] #return 2D_array of the first column

array([[ 3],
       [15],
       [27],
       [39],
       [51]])

### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [101]:
mat1 =  np.array([[15,16,17],[18,19,20],[21,22,23]])
mat2 =  np.array([[20,21,22],[23,24,25],[26,27,28]])

print(mat1 * mat2)

[[300 336 374]
 [414 456 500]
 [546 594 644]]


### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [102]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
horizontal_stacked_arr = np.hstack([arr1, arr2])
vertical_stacked_arr = np.vstack([arr1, arr2])
print(horizontal_stacked_arr)
print('-------------')
print(vertical_stacked_arr)

[1 2 3 4 5 6]
-------------
[[1 2 3]
 [4 5 6]]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [103]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [104]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [105]:
class Vehicle:
    def __init__(self, name, max_speed, mileage):
      self.name = name
      self.max_speed = max_speed
      self.mileage = mileage
    def seating_capacity(self, capacity=50):
      return "The seating capacity of a {} is {} passengers".format(self.name, self.capacity)

In [106]:
class Bus(Vehicle):
    def __init__(self, name, max_speed, mileage, ticket_price):
       Vehicle().__init__(self, name, max_speed, mileage)
       self.ticket_price = ticket_price

# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [ ]:
# Problem_1 Link:
numbers = [int(x) for x in input().split('+')]

numbers.sort()
numbers_as_chars = [str(x) for x in numbers]

result = '+'.join(numbers_as_chars)
print(result)

<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [110]:
# Problem_2 Link:
str = input().lower()
vowels = 'aeiouy'
result = ''
for char in str:
    if char in vowels:
        continue
    else:
        result = result + '.' + char

print(result)




MohamEd
.m.h.m.d
